apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-service-env
data:
  LOGGING_LEVEL_ORG_JAVAMONEY_MONETA: "OFF"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-server:5432/training"
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_DATASOURCE_PASSWORD: "admin"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_GENERATE_DDL: "true"
  SPRING_JPA_OPEN_IN_VIEW: "false"
  SPRING_MESSAGES_BASENAME: "exceptions"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka-server-pod:9092"
  SPRING_CLOUD_STREAM_BINDINGS_PAYMENTS-OUT-0_DESTINATION: "payment-events"
  API_TIME: "http://worldtimeapi.org/api/timezone/Europe/Warsaw"