apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-server-pod
  labels:
    app: zookeeper-server
spec:
  restartPolicy: OnFailure
  containers:
    - name: zookeeper-server
      image: wurstmeister/zookeeper
      ports:
        - containerPort: 2181
          name: client
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"